### ISSUE TITLE
warning: Getting  a ref that ends with 40 hex characters

### ISSUE THREAD

**Issue by chankruze** [ffulm/firmware#22]
```
chankruze@resonance-2:~/openwrt$ cd feeds/routing
chankruze@resonance-2:~/openwrt/feeds/routing$ git am --whitespace=nowarn ../../firmware/patches/routing/*.patch
Applying: alfred: adjust intervals
warning: refname '1b9d1c419f0ecefda51922a7845ab2183d6acd76' is ambiguous.
Git normally never creates a ref that ends with 40 hex characters
because it will be ignored when you just specify 40-hex. These refs
may be created by mistake. For example,

  git checkout -b $br $(git rev-parse ...)

where "$br" is somehow empty and a 40-hex ref is created. Please
examine these refs and maybe delete them. Turn this message off by
running "git config advice.objectNameWarning false"
chankruze@resonance-2:~/openwrt/feeds/routing$ 
```

**Comment by chankruze** [comment]
I think there is no need of the following in build commands in README ...
```
    cd feeds/routing
    git am --whitespace=nowarn ../../firmware/patches/routing/*.patch
    cd ../../
```
This is changing directory into feed/routing but applying patches 2levels up ... which is in the openwrt root folder ....and after that changing directory back to openwrt.

So i believe this patch can be apploed same as openwrt patches from root working directory.

```
git am --whitespace=nowarn firmware/patches/openwrt/*.patch
git am --whitespace=nowarn firmware/patches/routing/*.patch
```
And this doesn't producing ref that ends with 40 hex characters warning.I have forked and updated the README.md.
The pull request #23  have these changes.

**Comment by mwarning** [comment]
`feeds/routing` contains a different git repository. So this approach won't work.

**Comment by chankruze** [comment]
> `feeds/routing` contains a different git repository. So this approach won't work.

Maybe i am wrong. The warning don't appear necessarily don't mean that it is fixed,maybe the patch is not applying.
Kindly check that refs issue.

**Comment by chankruze** [comment]
This issue is fixed now.

**Comment by mwarning** [comment]
```
git am --whitespace=nowarn firmware/patches/routing/*.patch
```
This executed in the openwrt folder will create a new file `alfred/patches/0001-alfred-adjust-intervals.patch`, but not `feeds/routing/alfred/patches/0001-alfred-adjust-intervals.patch`.
It only kind of works, because there is only one patch and it creates a new file. If the patch would try to modify a file, an error would be triggered.

**Comment by chankruze** [comment]
This is fixed ... now not giving 40 character hex error from inside the routing folder.It's all working.I don't know what happened in the source tree but that commit it not conflicting now.

**Comment by mwarning** [comment]
ok :-)
