### ISSUE TITLE
IPERF3

### ISSUE THREAD

**Issue by ghost** [ffulm/firmware#28]
Cool wäre ein IPERF3 in der Firmware und der HTML-GUI
Dann könnte man auch Automatisch auswerten und an den Meshviewer melden.
Und auch ne TOP Rangliste der besten Anbindungen machen im Mershviewer

**Comment by mwarning** [comment]
Das routing Protokol (batman-adv) meldet bereits geschätzte Daten an die Karte. Allerdings wird das noch nicht angezeigt. Für VPN Verbindungen wird zwar keine Schätzung durchgeführt. Allerdings sich die Verbindungen id.R. bei weitem besser als WLAN Verbindungen und eher weniger Interessant.

Auf den Routern ist auch nicht mehr viel Platz für zusätzliche Programme..
