### ISSUE TITLE
ntp does not always work

### ISSUE THREAD

**Issue by saraedum** [ffulm/firmware#3]
nodes which have no direct connection to the internet usually fail to use ntp. They try to resolve the ntp servers configured in config/system. They resolve to ipv4 addresses. However, such nodes can not connect over ipv4.

**Comment by mwarning** [comment]
There is an OpenWrt ticket: https://dev.openwrt.org/ticket/12167
I've attached a patch. Maybe you could try if it works for you?
`/usr/sbin/ntpd -dn -p 2.openwrt.pool.ntp.org``

**Comment by mwarning** [comment]
We also might want to add the DNS server from the FF-network to /tmp/resolv.conf.lan.auto (aka /etc/resolv.conf), see: https://github.com/ffulm/firmware/blob/master/files/etc/hotplug.d/iface/40-freifunk#L13

**Comment by mwarning** [comment]
With the patch and the FF-Gateway in /etc/resolv.conf I get this:

```
root@OpenWrt:~# /usr/sbin/ntpd -dn -q -p 2.openwrt.pool.ntp.org
ntpd: resolved peer 2.openwrt.pool.ntp.org to 2001:418:3ff::53
ntpd: sending query to 2001:418:3ff::53
ntpd: reply from 2001:418:3ff::53: offset:+0.002574 delay:0.099571 status:0x24 strat:2 refid:0x82951115 rootdelay:0.013519 reach:0x01
ntpd: resolved peer 2.openwrt.pool.ntp.org to 213.154.229.24
ntpd: sending query to 213.154.229.24
ntpd: send failed: Network is unreachable
ntpd: resolved peer 2.openwrt.pool.ntp.org to 2a00:1ca8:e:4::b3b6:1d74
ntpd: sending query to 2a00:1ca8:e:4::b3b6:1d74
ntpd: reply from 2a00:1ca8:e:4::b3b6:1d74: offset:-0.003210 delay:0.093959 status:0x24 strat:3 refid:0x29518a21 rootdelay:0.005768 reach:0x05
ntpd: resolved peer 2.openwrt.pool.ntp.org to 85.255.214.66
ntpd: sending query to 85.255.214.66
ntpd: send failed: Network is unreachable
ntpd: resolved peer 2.openwrt.pool.ntp.org to 2001:418:3ff::53
ntpd: sending query to 2001:418:3ff::53
```

Looks okay (reply from 2a00:1ca8:e:4::b3b6:1d74).

**Comment by mwarning** [comment]
The patch is up, but /et/resolv.conf still needs to be populated.

**Comment by mwarning** [comment]
removing this line should do the job: https://github.com/ffulm/firmware/blob/master/files/etc/init.d/freifunk_setup#L158

Can you please test if this works for you?
